server:
  port: 8088

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://192.168.125.128:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect
    username: root
    password: root